spring:
  profiles:
    active: ${profile:dev}
  servlet:
    multipart:
      max-file-size: 26541661
      max-request-size: 26541661
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${filePath}
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto
  type-aliases-package: com.youaodu.template.common.entity.model, com.youaodu.template.common.framework.config.entity
  type-aliases-super-type: com.youaodu.template.common.framework.crud.BaseEntity
server:
  port: 8890